storeFile=../evaluator-signing/artinus-ocr-upload.jks
storePassword=DfB8LnS6V4R692K1kKTgLTyTm4KxoGNg6zGgbKA4iJDGIRT4uC5H69bm0K/xEwpT
keyAlias=artinus-ocr-upload
keyPassword=DfB8LnS6V4R692K1kKTgLTyTm4KxoGNg6zGgbKA4iJDGIRT4uC5H69bm0K/xEwpT
